using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace epj.RouteGenerator;

[Generator]
public class RouteGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var syntaxProvider = context.SyntaxProvider.CreateSyntaxProvider(
                (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(c => c is not null);

        var compilation = context.CompilationProvider.Combine(syntaxProvider.Collect());

        context.RegisterSourceOutput(compilation, Execute);
    }

    private void Execute(SourceProductionContext context, (Compilation Left, ImmutableArray<ClassDeclarationSyntax> Right) compilationTuple)
    {
        var (compilation, classes) = compilationTuple;

        var attributeSymbol = compilation.GetTypeByMetadataName("epj.RouteGenerator.AutoRouteGenerationAttribute");

        if (attributeSymbol is null)
        {
            // Stop the generator if no such attribute has been found
            return;
        }

        var classesWithAttribute = GetAllClasses(compilation.GlobalNamespace)
            .Where(t => t.GetAttributes().Any(ad => ad?.AttributeClass is not null && ad.AttributeClass.Equals(attributeSymbol, SymbolEqualityComparer.Default)))
            .ToList();

        if (!classesWithAttribute.Any())
        {
            // Stop the generator if no classes with the attribute have been found
            return;
        }

        var namespaceName = classesWithAttribute.First().ContainingNamespace.ToDisplayString();

        var pageClasses = classes.Where(c => c.Identifier.Text.EndsWith("Page")).ToList();

        var list = new List<string>();

        foreach (var pageClass in pageClasses)
        {
            list.Add(pageClass.Identifier.Text);
        }

        var classDeclarations = list.Select(page => $"public const string {page} = \"{page}\";");
        var classDeclarationsString = string.Join("\n    ", classDeclarations);

        var source = $$"""
                       // <auto-generated/>
                       namespace {{namespaceName}};

                       public static class Routes
                       {
                           {{classDeclarationsString}}

                           public static List<string> AllRoutes = new()
                           {
                               {{string.Join(",\n        ", list)}}
                           };
                       }
                       """;

        context.AddSource("Routes.g.cs", source);
    }

    // Helper method to get all classes in a namespace
    private static IEnumerable<INamedTypeSymbol> GetAllClasses(INamespaceSymbol namespaceSymbol)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            if (member is INamespaceSymbol childNamespace)
            {
                foreach (var childClass in GetAllClasses(childNamespace))
                {
                    yield return childClass;
                }
            }
            else if (member is INamedTypeSymbol classSymbol && classSymbol.TypeKind == TypeKind.Class)
            {
                yield return classSymbol;
            }
        }
    }
}
